urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin

from app.views import *
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
print admin.autodiscover()
print "autodiscovered.."

urlpatterns = patterns('',
    (r'^recommended/', recommended),
    (r'^options', options),
    (r'^course/(\w+)/(\w+)/?$', course),
    (r'^course/(\w+)/?$', course),
    (r'^add/(\w+)/(\w+)/?', add),
    (r'^semester/(\d{4})/(\w+)/?$', semester),
    (r'^admin/?', include(admin.site.urls)),
    (r'^transcript-import/?$', transcript_import),
    (r'^transcript-import/submit$', transcript_import_submit),
    (r'^recommendations-admin/clear$', recommendations_admin_clear),
    (r'^recommendations-admin/generate$', recommendations_admin_generate),
    (r'^accounts/login/$', 'django.contrib.auth.views.login'), 
    (r'^login/', user_login),
    (r'', index),
)

app/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
  # At the moment, we aren't using this class (we're using User instead)
  user = models.OneToOneField(User)
  graduation_date = models.DateField()

  def __str__(self):
    return str(self.user)

class Course(models.Model):
  #technically, this is all we need since we can just query
  #for the rest
  course_id = models.IntegerField(max_length=10)
  name = models.CharField(max_length=100, primary_key=True)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return "/courses/%s/" % self.id

class Semester(models.Model):
  owner = models.ForeignKey(User, related_name="semesters")
  courses = models.ManyToManyField(Course)

  year = models.IntegerField(max_length=4)
  SEMESTER_CHOICES = (
      ('F', 'Fall'),
      ('S', 'Spring'),
      ('U', 'Summer'),
  )
  semester = models.CharField(max_length=1, choices=SEMESTER_CHOICES)

  def get_absolute_url(self):
    return "/semester/%s/%s/" % (self.year, self.semester)

  def __str__(self):
    return "%s: %s %s" % (str(self.owner), str(self.year), str(self.semester))

class CourseLogProb(models.Model):
  predicate_cid = models.IntegerField()
  given_cid = models.IntegerField()
  logprob = models.FloatField()

front-end/templates/add.html
<ul class="course_list">
  {% for course in semester.courses.all %}
  <li>
  <div class="block">
    <span class="name">{{course.name}}</span>
    <div class="remove">

    </div>
  </div>
  </li> 
  {% endfor %}
</ul>

front-end/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  
  <link rel="stylesheet" href="{{STATIC_URL}}css/base.css">
  <link rel="stylesheet" href="{{STATIC_URL}}css/chosen.css">
  <link rel="stylesheet" href="{{STATIC_URL}}css/colorbox.css">

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
  <script src="{{STATIC_URL}}js/chosen.jquery.min.js"></script>
  <script src="{{STATIC_URL}}js/jquery.colorbox-min.js"></script>
  <script src="{{STATIC_URL}}js/base.js"></script>


  <title>{% block title %}Penn Course Planner{% endblock %}</title>

</head>

<body>

  <div id="title">
    <img src="http://www.seas.upenn.edu/~kevinsu/Logo.png" height="72" />
  </div>

  <br />

  {% block content %}{% endblock %}

</body>

<footer>

</footer>

</html>

front-end/templates/course.html
<div id="banner"/>

<h2>{{name}}</h2>

<!-- missing description!-->

{% for value in reviews.values %}
{% for field, rating in value.ratings.items %}
<span>{{field}}: {{rating}}</span>
<br/>
{% endfor %}
{% endfor %}


<div>
<button type="button" id="addClass">I've Taken This</button>
</div>

front-end/templates/index.html
{% extends "base.html" %}

{% block content %}

<div id="global">
  <div id="leftCol">
  </div>
  <div id="contentCol">
    <div id="headerArea">
      <h2>
        <span class="title">Your Classes</span>
      </h2>
    </div>
    <div id="contentArea">
      <div class="searchBox">
        <div id="search">
          <div class="padded">
            <select id="search-dept" data-placeholder="Type a department's name to add a course..." class="chzn-select search">
              <option value></option>
              {% for course in courses %}
              <option value="{{course}}">{{course}}</option>
              {% endfor %}
            </select>
          </div>

          <div class="padded">
            <select class="search" id="search-course" data-placeholder="Select a Class" style="display: none;">
              <option value></option>
            </select>
          </div>
        </div>
      </div>
      <div class="classList"></div>
    </div>
    <div id="rightCol">
      <div class="recommendBox">
        <div class="uiSection">
          <h3 class="suggestions">Course Suggestions</h3>
        </div>
        <div class="recommended"></div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

front-end/templates/options.html
<option value></option>
{% for course in courses %}
  <option value="{{course}}">{{course}}</option>
{% endfor %}

front-end/templates/recommended.html
<ul class="recommendedCourses">
  {% for course in courses %}
  <li class="suggestion">{{course|first}} ({{course|last}})<div class="wrong"></div></li>
  {% endfor %}
</ul>
<span class="more">See more suggestions</span>

front-end/templates/semester.html
{% extends "base.html" %}
{% load list %}

{% block content %}
    <p>Welcome {{user.first_name}}!</p>
    <h2>Courses in {{semester.get_semester_display}} {{semester.year}}</h2>
    {% list courses %}
    
    <h3>We recommend</h3>
    {% for course in recommended %}
      {{course.name}}
    {% endfor %}
{% endblock %}

front-end/templates/transcript_import.html
<!doctype html>
<html><head>
<title>Transcript Parser</title>
<script>

var TRANSCRIPT_START = "* * * * * UNIVERSITY OF PENNSYLVANIA COURSE WORK * * * * * *";
var REGEX_SEMESTER = /^(Spring|Summer|Fall) (\d{4})/;
var REGEX_COURSE = /^\s*(\w{2,4})\s+(\d{3})/;
var SEMESTERS = {Spring: "a", Summer: "b", Fall: "c"};
var FIRST_LINE = "(parsed)";

function getLines() {
    return document.getElementById("transcript").value.split("\n");
}

function parseTranscript() {
    lines = getLines();
    if (lines[0] == "(parsed)") {
        return;
    }

    var parsing = false;
    var currentSemester = "unknown";
    var data = {}
    for (var i=0, len = lines.length; i<len; i++) {
        var line = lines[i];

        if (line.indexOf("* *") == 0) {
            parsing = (line == TRANSCRIPT_START);
        } else if (parsing) {
            var semesterMatch = REGEX_SEMESTER.exec(line);
            var courseMatch = REGEX_COURSE.exec(line);
            if (semesterMatch) {
                currentSemester = semesterMatch[2] + SEMESTERS[semesterMatch[1]];
            } else if (courseMatch) {
                data[currentSemester] = data[currentSemester] || [];
                data[currentSemester].push(courseMatch[1] + " " + courseMatch[2])
            }
        }
    }
    var output = FIRST_LINE + "\n";
    for (var semester in data) {
        output += semester + ":" + data[semester] + "\n";
    }
    document.getElementById('transcript').value = output;
}

function submitCheck() {
    if (getLines()[0] != FIRST_LINE) {
        alert('Please parse the transcript first.');
        return false;
    }
   return true;
}

</script>
</head>

<body>
<h1>Transcript Parser</h1>
<p>We'd like to hear what courses you've taken. However, we don't want to know what your grades were, so this tool removes them from the text that's submitted to us.</p>
<ul>
    <li>Go to <a href="https://medley06.isc-seo.upenn.edu/pennInTouch/jsp/fast2.do?1=2&access=student">Penn InTouch</a>. Go to "Transcript and GPA" under "Academic Records."</li>
    <li><i>(optional)</i> Disable your internet connection.</li>
    <li>On your transcript page, select all and copy.</li>
    <li>Paste into the text box below.</li>
    <li>Click "Parse."</li>
    <li><i>(optional)</i> Copy the text in the textbox, reload this page, and paste back into the textbox.</li>
    <li>Reenable your internet connection.</li>
    <li>Click "Submit."</li>
</ul>
<form onSubmit="return submitCheck();" action="transcript-import/submit" method="post">
{% csrf_token %} 
<textarea cols="80" rows="20" id="transcript" name="courses"></textarea><br>
<input type="button" value="Parse" onClick="parseTranscript();"/>
<input type="submit"/>
</form>


</body> </html>